/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CmdFrame.java
 *
 * Created on 2009-12-2, 10:13:19
 */
package jndi;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrator
 */
public class CmdFrame extends javax.swing.JFrame {

    /** Creates new form CmdFrame */
    public CmdFrame() {
        initComponents();
        jTextPane1.addKeyListener(new KeyAdapter(){

            @Override
            public void keyPressed(KeyEvent e) {
               if(e.getKeyChar()=='\n'){
                    try {
                        run();
                    } catch (IOException ex) {
                        Logger.getLogger(CmdFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
               }
            }
        });
    }

    private void run() throws IOException {
        StringBuffer buffer = new StringBuffer();
        buffer.append(jTextPane1.getText());
        List<String> command = new ArrayList<String>();
        command.add(this.jTextPane1.getText());

        ProcessBuilder builder = new ProcessBuilder(command);
        builder.directory(new File(System.getenv("temp")));

        final Process process = builder.start();
        InputStream is = process.getInputStream();
        InputStreamReader isr = new InputStreamReader(is);
        BufferedReader br = new BufferedReader(isr);
        String line;
        while ((line = br.readLine()) != null) {
            buffer.append(line + "/n");
        }
        jTextPane1.setText(buffer.toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextPane1.setName("jTextPane1"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CmdFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
