/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 2010-12-27, 13:19:20
 */
package layout;

import java.awt.BorderLayout;

import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import testframe.IconUtils;

/**
 *
 * @author Administrator
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        final JDownComponentPanelContainer comtainer = new JDownComponentPanelContainer();
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new ListComponentPanelRenderer("A", "B", "C", "D", "E", "F", "G", "H", "I")));
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new ListComponentPanelRenderer("A", "B", "C", "D", "E", "F", "G", "H", "I")));
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new ListComponentPanelRenderer("A", "B", "C", "D", "E", "F", "G", "H", "I")));
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new ListComponentPanelRenderer("A", "B", "C", "D", "E", "F", "G", "H", "I")));
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new ListComponentPanelRenderer("A", "B", "C", "D", "E", "F", "G", "H", "I")));
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new ListComponentPanelRenderer("A", "B", "C", "D", "E", "F", "G", "H", "I")));
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new ListComponentPanelRenderer("A", "B", "C", "D", "E", "F", "G", "H", "I")));
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new ListComponentPanelRenderer("A", "B", "C", "D", "E", "F", "G", "H", "I")));
        AbstractAction action = new AbstractAction("Sample Action", IconUtils.getDownIcon()) {

            public void actionPerformed(ActionEvent e) {
                System.out.println(e.getActionCommand());
            }
        };
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new DownComponentMenu(new Action[]{action, action, action, action, action, action, action, action})));
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new DownComponentMenu(new Action[]{action, action, action, action, action, action, action, action})));
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new DownComponentMenu(new Action[]{action, action, action, action, action, action, action, action})));
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new DownComponentMenu(new Action[]{action, action, action, action, action, action, action, action})));
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new DownComponentMenu(new Action[]{action, action, action, action, action, action, action, action})));
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new DownComponentMenu(new Action[]{action, action, action, action, action, action, action, action})));
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new DownComponentMenu(new Action[]{action, action, action, action, action, action, action, action})));
        comtainer.addPopupPanel(new DownComponentPanel(new ButtonHeaderRenderer("open"), new DownComponentMenu(new Action[]{action, action, action, action, action, action, action, action})));
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(comtainer, BorderLayout.CENTER);
        final JDownComponentPanelContainer comtainer1 = new JDownComponentPanelContainer();
        action = new AbstractAction("Sample Action", IconUtils.getDownIcon()) {

            public void actionPerformed(ActionEvent e) {
                System.out.println(e.getActionCommand());
            }
        };
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setResizeWeight(1.0);
        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setOneTouchExpandable(true);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel2);

        jSplitPane1.setRightComponent(jScrollPane2);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
