/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 2011-3-1, 10:46:58
 */
package component;

import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author admin
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        this.groupButton1.addButton(new JButton("1"));
        this.groupButton1.addButton(new JButton("1"));
        this.groupButton1.addButton(new JButton("1"));
        this.groupButton1.addButton(new JButton("1"));
        this.groupButton1.addButton(new JButton("1"));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        groupButton1 = new component.GroupButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        groupButton1.setText(org.openide.util.NbBundle.getMessage(NewJFrame.class, "NewJFrame.groupButton1.text")); // NOI18N
        groupButton1.setName("groupButton1"); // NOI18N
        getContentPane().add(groupButton1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.GroupButton groupButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
