/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jp.co.toyoshimabs.plans.core;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class TimerTest extends javax.swing.JFrame {

    Timer timer;
    int start = 0;

    /** Creates new form TimerTest */
    public TimerTest() {
        initComponents();
        timer = new Timer(1000, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                timer.setRepeats(true);
                int temp = Calendar.getInstance().get(Calendar.MINUTE);
                jLabel1.setText((temp - start) + "");
                if (temp - start == 5) {
                    timer.stop();
                    JOptionPane.showMessageDialog(null, "时间到");
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");
        jLabel1.setName("jLabel1"); // NOI18N

        jButton1.setText("Start");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("End");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(62, 62, 62).addComponent(jLabel1).addContainerGap(65, Short.MAX_VALUE)).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jButton1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE).addComponent(jButton2).addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(33, 33, 33).addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton1).addComponent(jButton2)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        start = Calendar.getInstance().get(Calendar.MINUTE);
        timer.start();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        timer.stop();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        char[] abc = {'1', '2', '3'};
        String str1 = new String(abc);
        System.out.println("字符串为：" + str1);
//获取指定字节的构造器
        char[] abcd = {'1','1','3','4','5','6'};
        String str2 = new String(abcd, 3, 2);
        System.out.println("字符串为" + str2);
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration
}
