/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DrawPanel.java
 *
 * Created on 2009-8-26, 10:22:04
 */
package test;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;

/**
 *
 * @author Administrator
 */
public class DrawPanel extends javax.swing.JPanel {

    Color color[] = new Color[]{Color.RED, Color.GREEN, Color.YELLOW, Color.yellow, Color.blue};
    BufferedImage image[] = new BufferedImage[100];
    BufferedImage viewImage;

    /** Creates new form DrawPanel */
    public DrawPanel() {
        initComponents();
        this.setDoubleBuffered(true);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2D = (Graphics2D) g;
//        long timer = System.nanoTime();
//        g2D.drawImage(viewImage, 0, 0, this);
//        System.out.println(System.nanoTime() - timer);
        this.drawImage(g2D);
    }

    void drawImage(Graphics2D g) {
        long timer = System.nanoTime();
        Rectangle drawRect = this.getVisibleRect();
        Rectangle.Float tempRect = new Rectangle.Float();
        for (int i = 0; i < 100; i++) {
            tempRect.x = i * (drawRect.width / 100);
            if (image[i] != null) {
                g.drawImage(image[i], i * (drawRect.width / 100), 0, this);
            }
        }
        System.out.println(System.nanoTime() - timer);
    }

    void drawLine(Graphics2D g) {
        long timer = System.nanoTime();
        Rectangle drawRect = this.getVisibleRect();
        for (int i = 0; i < drawRect.width; i++) {
            g.setColor(color[i % 5]);
            g.drawLine(i, 0, i, drawRect.height);
        }
        System.out.println(System.nanoTime() - timer);
    }

    void fillShape(Graphics2D g) {
        long timer = System.nanoTime();
        Rectangle drawRect = this.getVisibleRect();
        Rectangle.Float tempRect = new Rectangle.Float();
        for (int i = 0; i < 100; i++) {
            tempRect.x = i * (drawRect.width / 100);
            tempRect.y = 0;
            tempRect.width = drawRect.width / 100;
            tempRect.height = drawRect.height;
            g.setColor(color[i % 5]);
            g.fill(tempRect);
        }
        System.out.println(System.nanoTime() - timer);
    }

    public void createIamge() {
        Rectangle drawRect = this.getVisibleRect();
        viewImage = new BufferedImage((int) drawRect.width, (int) drawRect.height, BufferedImage.TYPE_3BYTE_BGR);
        Graphics2D g2D = viewImage.createGraphics();
        g2D.setColor(Color.RED);
        g2D.fill(drawRect);
        Rectangle.Float tempRect = new Rectangle.Float();
        for (int i = 0; i < 100; i++) {
            tempRect.x = i * (drawRect.width / 100);
            tempRect.y = 0;
            tempRect.width = drawRect.width / 100;
            tempRect.height = drawRect.height;
            image[i] = new BufferedImage((int) tempRect.width, (int) tempRect.height, BufferedImage.TYPE_3BYTE_BGR);
            g2D = image[i].createGraphics();
            g2D.setColor(this.color[i % 5]);
            g2D.fill(tempRect);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        this.createIamge();
        repaint();
    }//GEN-LAST:event_formMouseWheelMoved

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
