/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJPanel.java
 *
 * Created on 2011-11-8, 13:09:23
 */
package document;

/**
 *
 * @author Zhenhai.Xu
 */
public class NewJPanel extends javax.swing.JPanel {

    /** Creates new form NewJPanel */
    public NewJPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.setName("jButton1"); // NOI18N
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButton2.setText("jButton2");
        jButton2.setName("jButton2"); // NOI18N
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jButton3.setText("jButton3");
        jButton3.setName("jButton3"); // NOI18N
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jButton4.setText("jButton4");
        jButton4.setName("jButton4"); // NOI18N
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jButton5.setText("jButton1");
        jButton5.setName("jButton5"); // NOI18N
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jButton6.setText("jButton2");
        jButton6.setName("jButton6"); // NOI18N
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jButton7.setText("jButton3");
        jButton7.setName("jButton7"); // NOI18N
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jButton8.setText("jButton4");
        jButton8.setName("jButton8"); // NOI18N
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jButton9.setText("jButton1");
        jButton9.setName("jButton9"); // NOI18N
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jButton10.setText("jButton2");
        jButton10.setName("jButton10"); // NOI18N
        add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jButton11.setText("jButton3");
        jButton11.setName("jButton11"); // NOI18N
        add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jButton12.setText("jButton4");
        jButton12.setName("jButton12"); // NOI18N
        add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jButton13.setText("jButton1");
        jButton13.setName("jButton13"); // NOI18N
        add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jButton14.setText("jButton2");
        jButton14.setName("jButton14"); // NOI18N
        add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jButton15.setText("jButton3");
        jButton15.setName("jButton15"); // NOI18N
        add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jButton16.setText("jButton4");
        jButton16.setName("jButton16"); // NOI18N
        add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jButton17.setText("jButton1");
        jButton17.setName("jButton17"); // NOI18N
        add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jButton18.setText("jButton2");
        jButton18.setName("jButton18"); // NOI18N
        add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jButton19.setText("jButton3");
        jButton19.setName("jButton19"); // NOI18N
        add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jButton20.setText("jButton4");
        jButton20.setName("jButton20"); // NOI18N
        add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
