/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VolatileImageFrame.java
 *
 * Created on 2009-9-7, 13:06:17
 */

package MaskImage;

/**
 *
 * @author Administrator
 */
public class VolatileImageFrame extends javax.swing.JFrame {

    /** Creates new form VolatileImageFrame */
    public VolatileImageFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volatileImagePane1 = new MaskImage.VolatileImagePane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        javax.swing.GroupLayout volatileImagePane1Layout = new javax.swing.GroupLayout(volatileImagePane1);
        volatileImagePane1.setLayout(volatileImagePane1Layout);
        volatileImagePane1Layout.setHorizontalGroup(
            volatileImagePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        volatileImagePane1Layout.setVerticalGroup(
            volatileImagePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(volatileImagePane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VolatileImageFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MaskImage.VolatileImagePane volatileImagePane1;
    // End of variables declaration//GEN-END:variables

}
